// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLWuSRrd5eUBYoDs-9gqxS5gnxrpjnqw',
    appId: '1:343711179856:web:df28eeb8d43c386a761d55',
    messagingSenderId: '343711179856',
    projectId: 'flutterproject-8672f',
    authDomain: 'flutterproject-8672f.firebaseapp.com',
    storageBucket: 'flutterproject-8672f.appspot.com',
    measurementId: 'G-XH0XSEQFXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqWIdl534lHzNT7mK35FJQwTAI_6dsumY',
    appId: '1:343711179856:android:71a56d7285fc8cb1761d55',
    messagingSenderId: '343711179856',
    projectId: 'flutterproject-8672f',
    storageBucket: 'flutterproject-8672f.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJLWuSRrd5eUBYoDs-9gqxS5gnxrpjnqw',
    appId: '1:343711179856:web:1cd95cce06354af8761d55',
    messagingSenderId: '343711179856',
    projectId: 'flutterproject-8672f',
    authDomain: 'flutterproject-8672f.firebaseapp.com',
    storageBucket: 'flutterproject-8672f.appspot.com',
    measurementId: 'G-35GKV1MBR9',
  );
}
